# Generated by Django 5.0.1 on 2024-03-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('date_posted', models.DateField()),
                ('employer_organization', models.CharField(max_length=255)),
                ('duration_in_months', models.IntegerField(default=0)),
                ('career_type', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Expired', 'Expired')], default='Pending', max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
